config/routes.rb
Rails.application.routes.draw do
  # Routes CRUD simplifiées
  resources :comments
  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :users

  # Route de vérification de santé de l'application
  get "up" => "rails/health#show", as: :rails_health_check

  # Définition de la route racine, vous pouvez choisir la page appropriée comme racine
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :content, presence: true, length: { maximum: 500, message: :content_length }

  before_save :set_depth

  def parent_comment_belongs_to_same_post
    if parent && parent.post != post
      errors.add(:parent_id, :same_post_error)
    end
  end

  def comment_depth
    if parent && depth > 3
      errors.add(:base, :depth_error)
    end
  end

  def depth
    read_attribute(:depth) || calculate_depth
  end

  private

  def set_depth
    self.depth = calculate_depth
  end

  def calculate_depth
    parent ? parent.depth + 1 : 0
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :comments, dependent: :destroy # Supprime les commentaires associés si le post est supprimé

  # Validations
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true

  # Scopes (exemple si nécessaire)
  # scope :published, -> { where(published: true) }

  # Méthode pour voter positivement
  def upvote
    increment!(:upvotes)
  end

  # Méthode pour voter négativement
  def downvote
    increment!(:downvotes)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  VALID_PASSWORD_REGEX = /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,64}\z/
  VALID_NAME_REGEX = /\A[a-zA-Z\s]+\z/

  validates :name, presence: true, length: { in: 3..16 }, format: { with: VALID_NAME_REGEX, message: :name_format }
  validates :password, presence: true, length: { in: 8..64 }, format: { with: VALID_PASSWORD_REGEX, message: :password_format }
  #validates :password_confirmation, presence: true, message: :password_confirmation_presence
  validates :email, presence: true, uniqueness: { message: :email_uniqueness }, format: { with: URI::MailTo::EMAIL_REGEXP, message: :email_format }

# Scopes (exemple si nécessaire)
  # scope :active, -> { where(active: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
    # @comment is already set by the before_action
  end

  # GET /comments/new
  def new
    #@comment = Comment.new(comment_params)
    @comment = Comment.new
    # Rails.logger.info "Received comment params in new comment: #{comment_params.inspect}"
    @comment.post_id = params[:post_id] if params[:post_id]
    @comment.parent_id = params[:parent_id] if params[:parent_id]
  end

  # POST /comments
  def create
    Rails.logger.info "Received comment params in create comment: #{comment_params.inspect}"
    @comment = Comment.new(comment_params)
    @comment.user_id = rand(1..10)  # Attribuer un user_id aléatoire

    if @comment.save
      redirect_to @comment.post, notice: 'Comment was successfully created.'
    else
      @post = Post.find(@comment.post_id)  # Récupérer le post pour le formulaire en cas d'erreur
      render :new
    end
  end

  # GET /comments/1/edit
  def edit
    # @comment is already set by the before_action
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

    # DELETE /comments/1
    def destroy
      post = @comment.post  # Conserver le post avant la suppression pour la redirection
      @comment.destroy
      redirect_to post, notice: 'Comment was successfully destroyed.'
    end

      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = Comment.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def comment_params
        params.require(:comment).permit(:content, :post_id, :parent_id, :comment_id)
      end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def hello
    @greetings = "Hello !"
  end

  def toto
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1

    def show
      @post = Post.find(params[:id])
      @comment = Comment.new
    end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    # Assignation d'un user_id aléatoire entre 1 et 10 à new avant de passer à post_params
    @post = Post.new(post_params.merge(user_id: rand(1..10)))

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      # Affiche les messages d'erreur
      @post.errors.full_messages.each { |message| puts message }

      render :new
    end
  end


  # GET /posts/1/edit
  def edit
    # @post is already set by the before_action
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote
    redirect_to @post, notice: 'Merci pour votre vote positif!'
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote
    redirect_to @post, notice: 'Vote négatif enregistré.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end



  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :upvotes, :downvotes, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    # @user is already set by the before_action
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # GET /users/1/edit
  def edit
    # @user is already set by the before_action
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
# app/helpers/comments_helper.rb
module CommentsHelper
  def render_comments(comments, depth = 0)
    safe_join(comments.map do |comment|
      render(partial: 'comments/comment', locals: { comment: comment, depth: depth }) +
        render_comments(comment.children, depth + 1) unless comment.children.empty?
    end)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<!-- app/views/comments/_comment.html.erb -->
<div id="<%= dom_id(comment) %>" class="mt-4" style="margin-left: <%= 20 * comment.depth %>px;">
  <div class="space-y-2">
<!--    <p class="text-gray-500">Depth: <%#= comment.depth %></p>-->
    <p class="text-gray-800"><strong>Content:</strong> <%= comment.content %></p>
    <p class="text-sm text-gray-600"><strong>Author:</strong> <%= comment.user.name %></p>
    <p class="text-sm text-gray-600"><%= link_to t('buttons.edit'), edit_comment_path(commit_id: comment.id), class: "inline-block px-3 py-1 text-sm font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 transition-colors duration-150 ease-in-out" %></p>

    <%= link_to t('buttons.answer_comment'), new_comment_path(parent_id: comment.id, post_id: comment.post_id), class: "inline-block px-3 py-1 text-sm font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 transition-colors duration-150 ease-in-out" %>

    <% if comment.replies.any? %>
      <div class="mt-4">
        <strong class="text-gray-800">Child Comments:</strong>
        <% comment.replies.each do |child_comment| %>
          <%= render 'comments/comment', comment: child_comment %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true, id: dom_id(comment), class: "max-w-lg mx-auto shadow-md overflow-hidden rounded-lg") do |form| %>
  <% if comment.errors.any? %>
    <div class="bg-red-100 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold"><%= pluralize(comment.errors.count, "error") %></strong>
      <span class="block sm:inline">prohibited this comment from being saved:</span>
      <ul class="list-disc pl-5">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :post_id, value: @comment.post_id %>

  <% if @comment.parent_id.present? %>
    <%= form.hidden_field :parent_id, value: @comment.parent_id %>
  <% end %>


  <div class="px-6 py-4">
    <%= form.label :content, I18n.t('activerecord.attributes.comment.content'), class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :content, rows: 4, class: 'mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm' %>
  </div>

  <div class="px-6 py-4 bg-gray-50 text-right">
    <%= form.submit I18n.t('helpers.submit.create', model: Comment.model_name.human), class: 'inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
  </div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<div class="max-w-7xl mx-auto px-6 py-10 bg-white shadow-lg rounded-lg">
  <h1 class="text-3xl font-bold text-gray-800 mb-6">Comments#edit</h1>
  <p class="mb-8 text-gray-600">Find me in app/views/comments/edit.html.erb</p>
  <%= link_to t("buttons.back"), comments_path, class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-8" %>

  <%= form_with model: @comment, class: "space-y-6" do |form| %>
    <%= form.hidden_field :post_id, value: @comment.post_id %>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div class="col-span-1 md:col-span-2">
        <%= form.label :content, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_area :content, rows: 5, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
    </div>

    <div class="flex justify-end">
      <%= form.submit t("buttons.edit"), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="text-4xl font-bold text-gray-900 mb-8">Liste des commentaires</h1>

  <ul class="space-y-4">
    <% @comments.each do |comment| %>
      <li class="bg-white border border-gray-200 rounded-md p-4 shadow-sm hover:shadow-md transition-shadow duration-150 ease-in-out">
        <h3 class="text-xl font-semibold text-blue-500"><%= comment.post.title %></h3>
        <p class="text-gray-600"><%= comment.content %></p>
        <p class="text-sm text-gray-500"> <%= t("labels.user.postcreatedby") %> <%= comment.user.name %> <%= time_ago_in_words(comment.created_at) %></p>
        <div class="flex space-x-2 mt-3">
          <%= link_to t("buttons.show"), comment_path(comment), class: "px-4 py-2 text-sm text-white bg-blue-500 rounded-md hover:bg-blue-600 transition-colors duration-150 ease-in-out" %>
          <%= link_to t("buttons.edit"), edit_comment_path(comment), class: "px-4 py-2 text-sm text-white bg-green-500 rounded-md hover:bg-green-600 transition-colors duration-150 ease-in-out" %>
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to t("buttons.create_post"), new_post_path, class: "mt-8 inline-block px-6 py-3 text-lg font-medium text-white bg-red-500 rounded-md hover:bg-red-600 transition-colors duration-150 ease-in-out" %>
</div>

app/views/comments/new.html.erb
<div class="max-w-7xl mx-auto px-6 py-10 bg-white shadow-lg rounded-lg">
  <h1 class="text-3xl font-bold text-gray-800 mb-6">Comments#new</h1>
  <p class="mb-8 text-gray-600">Find me in app/views/comments/new.html.erb</p>
  <%= link_to t("buttons.back"), comments_path, class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-8" %>

  <%= form_with model: @comment, class: "space-y-6" do |form| %>
    <%= form.hidden_field :post_id, value: @comment.post_id %>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div class="col-span-1 md:col-span-2">
        <%= form.label :content, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_area :content, rows: 5, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
    </div>

    <div class="flex justify-end">
      <%= form.submit t("buttons.create"), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/comments/show.html.erb
<!-- app/views/comments/show.html.erb -->
<%= render @comment  %>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/home/index.html.erb
<div class="container mx-auto px-4 mt-8">

  <h2 class="text-2xl font-semibold mb-6" style="color: #FF4500;">Bienvenue sur RedditTP !</h2>

  <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
    <%= link_to t("buttons.showposts"), posts_path, class: "flex justify-center items-center px-6 py-3 border border-blue-500 text-lg font-medium rounded-md text-white bg-blue-500 hover:bg-blue-600 transition duration-150 ease-in-out shadow-md" %>
    <%= link_to t("buttons.showcomments"), comments_path, class: "flex justify-center items-center px-6 py-3 border border-orange-500 text-lg font-medium rounded-md text-white bg-orange-500 hover:bg-orange-600 transition duration-150 ease-in-out shadow-md" %>
    <%= link_to t("buttons.showusers"), users_path, class: "flex justify-center items-center px-6 py-3 border border-green-500 text-lg font-medium rounded-md text-white bg-green-500 hover:bg-green-600 transition duration-150 ease-in-out shadow-md" %>
  </div>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="max-w-4xl mx-auto px-4 py-8">
  <div class="bg-white border border-gray-200 rounded-lg p-6 shadow-lg space-y-4">
    <h3 class="text-2xl font-bold text-gray-900">Title: <%= post.title %></h3>
    <p class="text-gray-700">Content: <%= post.content %></p>
    <p class="text-sm text-gray-500">Créé: <%= time_ago_in_words(post.created_at) %> par <%= post.user.name %></p>


    <div class="grid grid-cols-2 gap-4">
      <div class="text-sm text-gray-500 flex items-center justify-center">
        Upvotes: <%= post.upvotes %>
      </div>
      <div class="text-sm text-gray-500 flex items-center justify-center">
        Downvotes: <%= post.downvotes %>
      </div>
      <div class="flex items-center justify-center">
        <%= form_with url: upvote_post_path(post), method: :post, local: true do |form| %>
          <button type="submit" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.25c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a.75.75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282m0 0h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c.472 0 .745.556.5.96a8.958 8.958 0 0 0-1.302 4.665c0 1.194.232 2.333.654 3.375Z" />
            </svg>
          </button>
        <% end %>
      </div>
      <div class="flex items-center justify-center">
        <%= form_with url: downvote_post_path(post), method: :post, local: true do |form| %>
          <button type="submit" class="btn btn-primary">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M7.498 15.25H4.372c-1.026 0-1.945-.694-2.054-1.715a12.137 12.137 0 0 1-.068-1.285c0-2.848.992-5.464 2.649-7.521C5.287 4.247 5.886 4 6.504 4h4.016a4.5 4.5 0 0 1 1.423.23l3.114 1.04a4.5 4.5 0 0 0 1.423.23h1.294M7.498 15.25c.618 0 .991.724.725 1.282A7.471 7.471 0 0 0 7.5 19.75 2.25 2.25 0 0 0 9.75 22a.75.75 0 0 0 .75-.75v-.633c0-.573.11-1.14.322-1.672.304-.76.93-1.33 1.653-1.715a9.04 9.04 0 0 0 2.86-2.4c.498-.634 1.226-1.08 2.032-1.08h.384m-10.253 1.5H9.7m8.075-9.75c.01.05.027.1.05.148.593 1.2.925 2.55.925 3.977 0 1.487-.36 2.89-.999 4.125m.023-8.25c-.076-.365.183-.75.575-.75h.908c.889 0 1.713.518 1.972 1.368.339 1.11.521 2.287.521 3.507 0 1.553-.295 3.036-.831 4.398-.306.774-1.086 1.227-1.918 1.227h-1.053c-.472 0-.745-.556-.5-.96a8.95 8.95 0 0 0 .303-.54" />
            </svg>
          </button>
        <% end %>
      </div>
    </div>



    <%= link_to t("buttons.add_comment"), new_comment_path(post_id: post.id), class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>

    <% if post.comments.any? %>
      <div class="mt-6">
        <h4 class="text-xl font-semibold text-gray-800 mb-2">Comments:</h4>
        <% post.comments.each do |comment| %>
          <div class="border border-gray-300 rounded-md p-4 mb-4 last:mb-0 shadow-sm">
            <%= render 'comments/comment', comment: comment %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<div class="max-w-lg mx-auto mt-8 bg-white shadow-md rounded-lg p-6">
  <h1 class="text-3xl font-bold mb-4">Modifier un post</h1>

  <%= link_to t("buttons.back"), posts_path, class: "inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-8" %>

  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="text-4xl font-bold text-gray-900 mb-4">Posts</h1>
  <p class="mb-8 text-lg text-gray-700">Voici tous les posts :</p>

  <ul class="space-y-4">
    <% @posts.each do |post| %>
      <li class="bg-white border border-gray-200 rounded-md p-4 shadow-sm hover:shadow-md transition-shadow duration-150 ease-in-out">
        <h3 class="text-xl font-semibold text-blue-500"><%= post.title %></h3>
        <p class="text-gray-600"><%= post.content %></p>
        <p class="text-sm text-gray-500"><%= t("labels.user.postcreatedby") %> <%= post.user.name %> <%= time_ago_in_words(post.created_at) %></p>
        <div class="flex space-x-2 mt-3">
          <%= link_to t("buttons.show"), post_path(post), class: "px-4 py-2 text-sm text-white bg-blue-500 rounded-md hover:bg-blue-600 transition-colors duration-150 ease-in-out" %>
          <%= link_to t("buttons.edit"), edit_post_path(post), class: "px-4 py-2 text-sm text-white bg-green-500 rounded-md hover:bg-green-600 transition-colors duration-150 ease-in-out" %>
          <%= link_to t("buttons.add_comment"), new_comment_path(post_id: post.id), class: "px-4 py-2 text-sm text-white bg-orange-500 rounded-md hover:bg-orange-600 transition-colors duration-150 ease-in-out" %>
          <!-- Le lien de suppression peut être stylisé de manière similaire si vous décidez de l'utiliser plus tard -->
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to t("buttons.add_post"), new_post_path, class: "mt-8 inline-block px-6 py-3 text-lg font-medium text-white bg-red-500 rounded-md hover:bg-red-600 transition-colors duration-150 ease-in-out" %>
</div>

app/views/posts/new.html.erb
<div class="max-w-lg mx-auto mt-8 bg-white shadow-md rounded-lg p-6">
  <h1 class="text-3xl font-bold mb-4">Nouveau Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to t("buttons.create_post"), new_post_path, class:"block text-center text-sm text-gray-600 hover:text-gray-800 mt-4"%>
</div>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->
<%= render @post  %>

app/views/users/_user.html.erb
<!-- app/views/users/_user.html.erb -->
<div id="<%= dom_id user %>" class="bg-white shadow rounded-lg p-4 mb-6">
  <p class="font-bold text-lg mb-2">
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p class="mb-2">
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <% if user.posts.any? %>
    <div class="mt-4">
      <strong>Posts:</strong>
      <ul class="list-disc pl-5">
        <% user.posts.each do |post| %>
          <li><%= link_to post.title, post_path(post), class: "text-indigo-600 hover:text-indigo-800" %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if user.comments.any? %>
    <div class="mt-4">
      <strong>Comments:</strong>
      <ul class="list-disc pl-5">
        <% user.comments.each do |comment| %>
          <li><%= render 'comments/comment', comment: comment %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div class="flex justify-between items-center py-6">
    <h1 class="text-2xl font-bold text-gray-900"><%= t('users.index.title') %></h1>
    <%= link_to t('users.index.new_user'), new_user_path, class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>

  <div id="users-list" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
    <% @users.each do |user| %>
      <div id="<%= dom_id user %>" class="bg-white shadow rounded-lg p-4">
        <h3 class="text-lg font-medium text-gray-900"><%= user.name %></h3>
        <p class="text-sm text-gray-500"><%= user.email %></p>
        <%= link_to t('users.index.show'), user_path(user), class: "mt-2 inline-flex items-center px-2 py-1 border border-transparent text-xs leading-4 font-medium rounded text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-2xl font-bold text-gray-900 py-6">New user</h1>

  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <%= render "form", user: @user %>
  </div>

  <div class="mt-6">
    <%= link_to t("buttons.back"), users_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
  </div>
</div>